### ISSUE TITLE
Crashes on Deploy using Docker

### ISSUE THREAD

**Issue by Type-32** [xtekky/chatgpt-clone#96]
I followed the steps (via installing requirements and doing python stuff) and when I do docker compose up the container crashes on start. This is the log from my portainer:
```
Running on port 8501
 * Serving Flask app 'server.app'
 * Debug mode: off
Address not available
```
I checked all my ports in docker-compose.yml and config.json to be of port 8501:8501 and 8501, but it does not work.

docker-compose.yml
```
version: '3.5'

services:
  chatgpt-clone:
    image: chatgpt-clone
    container_name: chatgpt-clone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
```

config.json
{```

    "site_config": {
        "host" : "0.0.0.0",
        "port" : 8501,
        "debug": false
    },
    "openai_key": "sk-[REDACTED]",

    "openai_api_base": "https://api.openai.com",
    "proxy": {
	"enable": false,
        "http": "127.0.0.1:7890",
        "https": "127.0.0.1:7890"
    }
}
```
